version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
      args:
        - CAAS_API_KEY=${CAT_API_KEY}
    ports:
      - "${API_PORT}:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CAT_API_KEY=${CAT_API_KEY}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

