services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5197:8081"  # Host:Container
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__SqlConnectionString=Server=db;Database=StealCatsDb;User=sa;Password=Your_password123;Encrypt=False;


  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

